### PR TITLE
fix: Revert "chore: add applets refresh after answers submission (#884)" (M2-8144)

### PR DESCRIPTION
**Pull request by farmerpaul**
### 📝 Description

🔗 [Jira Ticket M2-8144](https://mindlogger.atlassian.net/browse/M2-8144)

Reverting #884 as it only partially solved the issue (didn't fix it for offline), and may have introduced more regressions (to be confirmed by QA).

### 🪤 Peer Testing

N/A

### CODE REVIEW

**Review by sultanofcardio — APPROVED** [review]
@farmerpaul I think this PR should target the `release/2.5.0` branch, so QA can get it

**Comment by farmerpaul** [comment]
Ah right. I'll update the branch accordingly.

**Review by mbanting — APPROVED** [review]
Thanks for reverting and bumping the version.

**Comment by mbanting** [comment]
Since it's going to the release branch directly, any subsequent fix for 8144 will need to follow the same merging strategy. I'll make sure to create a PR to merge back to dev after production deployment.

**Pull request merged**
