### PR TITLE
feat: add Greek language option (M2-7800)

### PR DESCRIPTION
**Pull request by ChaconC**
### 📝 Description

Adds Greek language localization support.

🔗 [Jira Ticket M2-7800](https://mindlogger.atlassian.net/browse/M2-7800)

### iOS Screenshots
| 1 | 2 | 3 |
| -------------------------------------- | ------------------------------------- | - |
| Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 52 08 | Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 32 13 | Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-15 at 16 34 49 | 

### Android Screenshots
| 1 | 2 | 3 |
| -------------------------------------- | ------------------------------------- | - |
| Screenshot_1729032140 |Screenshot_1729032149 | Screenshot_1729032235 | 

### 🪤 Peer Testing

- Load App
- Navigate to Change Language menu or select language from login screen
- Select "Ελληνικά" from language screen

### Notes
A few strings were provided with "deprecated" instructions and are not translated. They will be removed in a future ticket (M2-7879).
Additionally, the translation vendor will be performing visual validation for long or strange strings.

### CODE REVIEW

**Comment by felipeMetaLab** [comment]
It looks good to me, the only thing I noticed is that there are some English parts in the translation file, but I opened Jira to better understand the task and the translation was already attached.

**Review by felipeMetaLab — DISMISSED** [review]

**Comment by felipeMetaLab** [comment]
I changed the language but there is a lot of parts in english yet.
1 first thing I changed the language:
Screenshot 2024-10-15 at 9 04 50 PM

Screens:
Screenshot 2024-10-15 at 9 04 43 PM
Screenshot 2024-10-15 at 9 04 58 PM
Screenshot 2024-10-15 at 9 05 09 PM
Screenshot 2024-10-15 at 9 08 31 PM
Screenshot 2024-10-15 at 9 09 54 PM

for some reason almost the entire app still in english.

I read the statement "A few strings were provided with "deprecated" instructions and are not translated. They will be removed in a future ticket" , so that's why my app wasn't translated?

**Comment by felipeMetaLab** [comment]
This is the branch I am using: feat/M2-7843-add_greek_language
Screenshot 2024-10-16 at 7 58 53 AM

I will detail the steps I followed:
1 - excluded the app,
2 - changed the branch
3 - I ran yarn - after cd ios, pod install
4 - I back to project root and yarn ios

**Comment by ChaconC** [comment]
@felipeMetaLab that branch is incorrect, please check which branch I'm trying to merge (`feat/M2-7843-greek_language`)

**Comment by felipeMetaLab** [comment]
yes, I am sorry, the only branch that appeared on my git was that, but you are right, I synced my git and now I am in correct branch and testing again

**Comment by felipeMetaLab** [comment]
I tested and its working fine.

**Review by felipeMetaLab — APPROVED** [review]

**Pull request merged**
