### PR TITLE
fix(markdown): Added html sanitizer when content includes html markdown

### PR DESCRIPTION
**Pull request by BamMironov**
**Requires `yarn install`**

[sanitize-html](https://github.com/apostrophecms/sanitize-html#readme) OSS package added to MindLogger

### 📝 Description

🔗 [Jira Ticket M2-5218](https://mindlogger.atlassian.net/browse/M2-5218)

This PR changes:

- The way how markdown content is preprocessed before sending over to the WebView

### 🪤 Peer Testing

Example test step:

- Edit an applet using Postman: PUT https://api-dev.cmiml.net/applets/${applet_id}.
- Assign "<script>alert('test 3')</script>"string to the `question.en` field image
- Process the request
- Go to the mobile app and perform Pull-to-Refresh operation to fetch the latest applet update.
- Go to the activity with the changes `question.en` field.

**Expected outcome:** No alert window pops up.

### CODE REVIEW

**Review by farmerpaul — APPROVED** [review]
Hey @BamMironov, the code looks fine to me, and after some trial & error was able to follow your instructions and test it, the the sanitizer works! (I had to first use my devtools to peek at an example PUT payload via the admin panel to get the correct payload structure.) Happy to approve.

**Review by mbanting — APPROVED** [review]
Does `sanitize-html` need to get added to the [open source credits](https://mindlogger.atlassian.net/servicedesk/customer/portal/3/topic/58298d10-396d-4e58-936f-e3b4e321972a/article/340623543)?

Either way, looks great @BamMironov! Thanks for the helpful PR documentation.

**Comment by BamMironov** [comment]
Thank you guys!

@mbanting It sure does! Yep, let's add it to the open-source credits.
It seems, however, that I don't have access to the page. Who would be the right person to ask about it?

**Comment by mbanting** [comment]
> Thank you guys!
> 
> @mbanting It sure does! Yep, let's add it to the open-source credits. It seems, however, that I don't have access to the page. Who would be the right person to ask about it?



> Thank you guys!
> 
> @mbanting It sure does! Yep, let's add it to the open-source credits. It seems, however, that I don't have access to the page. Who would be the right person to ask about it?

It gets added by updating this [page](https://mindlogger.atlassian.net/jira/servicedesk/projects/MLA/knowledge/articles/340623543?spaceKey=MLA)

I was recently given access so I went ahead and added `sanitize-html` and `@types/sanitize-html`. All good to go!

**Comment by BamMironov** [comment]
@mbanting Still can't see the page. Maybe that's because I don't have access to the Metalb's space on Jira. Can we create a page(s) that everyone has access to?

**Comment by farmerpaul** [comment]
According to @IhorNesterenko99 (when he [reviewed my admin panel PR](https://github.com/ChildMindInstitute/mindlogger-admin/pull/1464#discussion_r1479333687)), [this is the page in Confluence](https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/263127186/Admin+Panel+Applet+Builder+Library) that is supposed to be updated by engineers with new libraries introduced to the project. @BamMironov do you have access to that?

@mbanting the one that you linked to is similar to the one above, but I think yours actually lives in the help desk knowledge base (which not everyone has access to). I imagine it's supposed to get updated periodically by what's contained in Confluence? Not sure.

**Pull request merged**
