### PR TITLE
feat: added new UI for login screen

### PR DESCRIPTION
**Pull request by DimitrySakalouski**
android_phone

android_еtablet

ios

### CODE REVIEW

**Comment by BamMironov** [comment]
@DimitrySakalouski  can we limit the maximum width of the form? Like this:
Untitled

**Comment by BamMironov** [comment]
@DimitrySakalouski  please check the distances between objects. I think there are mismatches. For instance, take a look at the distance between the "Forgot Password" button and the form. Please see how to measure distances on Figma:
https://help.figma.com/hc/en-us/articles/360039956974-Measure-distances-between-layers

**Review by BamMironov — CHANGES_REQUESTED** [review]
The code is fine. Please work on design

**Comment by DimitrySakalouski** [comment]
image

**Comment by DimitrySakalouski** [comment]
image

**Comment by DimitrySakalouski** [comment]
image

**Comment by DimitrySakalouski** [comment]
image

**Comment by DimitrySakalouski** [comment]
image

**Comment by DimitrySakalouski** [comment]
image

**Review by BamMironov — APPROVED** [review]
Looks good to me

**Pull request merged**
